const siteMetaData = {
  keywords: ["", "", "", "", "", ""],
  title: "The Macrocosm Consortium",
  titleAlt: "",
  description: "If you zoom out far enough, the human race appears to be just a single organism.",
  url: "https://www.macrocosm.so/",
  siteUrl: "https://www.macrocosm.so/",
  siteLanguage: "en-US",
  logo: "https://www.macrocosm.so/",
  image: "https://www.myfirstnda.com/src/Thumbnail.png",
  favicon: "/favicon.ico",
  shortName: "Macrocosm",
  author: "The Macrocosm Consortium",
  themeColor: "#000000",
  backgroundColor: "#ffffff",
  twitterDesc: "If you zoom out far enough, the human race appears to be just a single organism.",
  twitter: "https://twitter.com/macrocosmcorp",
  locale: "en-US",
  ogLanguage: "en_US",
};
export default siteMetaData;
